# Generated by Django 4.2.19 on 2025-02-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='', max_length=255)),
                ('meta_description', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Article')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='horizon.author')),
            ],
        ),
    ]
