# Generated by Django 4.2.19 on 2025-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='read_time',
            field=models.IntegerField(default=1),
        ),
    ]
