# Generated by Django 4.2.19 on 2025-02-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0002_content_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
