# Generated by Django 4.2.19 on 2025-02-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0003_content_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='featured_image',
            new_name='image_featured',
        ),
        migrations.AddField(
            model_name='content',
            name='image_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='image_caption',
            field=models.CharField(default='', max_length=255),
        ),
    ]
