# Generated by Django 4.2.19 on 2025-02-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0005_remove_content_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='horizon.category'),
        ),
    ]
