# Generated by Django 4.2.19 on 2025-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0008_tag_content_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
        migrations.AddField(
            model_name='content',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='contents', to='horizon.tag'),
        ),
    ]
