# Generated by Django 4.2.19 on 2025-02-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0009_remove_content_tag_content_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='tag',
            new_name='tags',
        ),
    ]
