# Generated by Django 4.2.19 on 2025-02-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0010_rename_tag_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='html_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
