# Generated by Django 4.2.19 on 2025-02-23 19:39

from django.db import migrations, models
import horizon.models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0011_content_html_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=horizon.models.image_upload_to, validators=[horizon.models.validate_jpg_and_size])),
            ],
        ),
    ]
