# Generated by Django 4.2.19 on 2025-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0012_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='uploaded_to',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
