# Generated by Django 4.2.19 on 2025-02-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0013_uploadedimage_uploaded_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='uploaded_to',
        ),
    ]
