# Generated by Django 4.2.19 on 2025-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0014_remove_uploadedimage_uploaded_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_featured_srcset',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
