# Generated by Django 4.2.19 on 2025-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0015_content_image_featured_srcset'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image_srcset',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
