# Generated by Django 4.2.19 on 2025-02-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0016_author_profile_image_srcset'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
