# Generated by Django 4.2.19 on 2025-02-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0017_content_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
