# Generated by Django 4.2.19 on 2025-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0018_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='horizon.category'),
        ),
    ]
